action: Merge SBOMs
description: Uses CycloneDX to merge SBOMs
inputs:
  input-files-pattern:
    description: "pattern of files to"
    required: true
    default: "/github/workspace/.sboms/*.xml"
  output-file:
    description: Merged SBOM output location.
    required: true
    default: ".sboms/merged.xml"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input-files-pattern }}
    - ${{ inputs.output-file }}

